name: Build Rust AWS Lambda

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Show environment
      run: cargo --version

    - name: Run checks
      run: cargo fmt -- --check
      
    - name: Run tests
      run: cargo test --verbose

    - name: Add target 
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-musl

    - name: Create `.bootstrap` executable
      run: cp ./target/x86_64-unknown-linux-musl/release/rs_test_aws_lambda ./bootstrap
      
    - name: Make deployment package .zip file
      run: |
        zip lambda.zip bootstrap
        ls -la

    - name: Update Lambda in AWS
      run: aws lambda update-function-code --function-name rs_test_aws_lambda --zip-file fileb://./lambda.zip --publish
      env:
        AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Archive deployment package
      uses: actions/upload-artifact@v2
      with:
        name: lambda.zip
        path: ./lambda.zip
